Modified Steps to skip deployment if EKS cluster is deleted for cost saving

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,8 +35,16 @@ jobs:
     - name: Update kubeconfig for EKS
       run: aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
 
+    # Adding this step to avoid failure after clean-up(for cost savings)
+    - name: Check EKS cluster exists
+      run: |
+        if ! aws eks describe-cluster --name $EKS_CLUSTER_NAME --region $AWS_REGION; then
+          echo "EKS cluster not found, skipping deployment"
+          exit 0
+        fi
+
     - name: Deploy to EKS
       run: |
         kubectl apply -f k8s/nginx-deployment.yml
         kubectl apply -f k8s/nginx-service.yml
-
+	
